version: '3.8'

services:
  n8n:
    image: my-n8n:latest
    ports:
      - "${N8N_PORT:-5678}:${N8N_PORT:-5678}"
    entrypoint: ["/container_run.sh"]
    volumes:
      - ./container_run.sh:/container_run.sh:ro
      - n8n_data:/root/.n8n
    environment:
      - DB_TYPE=postgresdb

      - N8N_BASIC_AUTH_USER_FILE=/run/secrets/N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD_FILE=/run/secrets/N8N_BASIC_AUTH_PASSWORD
      - N8N_ENCRYPTION_KEY_FILE=/run/secrets/N8N_ENCRYPTION_KEY
      - DB_POSTGRESDB_HOST_FILE=/run/secrets/DB_POSTGRESDB_HOST
      - DB_POSTGRESDB_PORT_FILE=/run/secrets/DB_POSTGRESDB_PORT
      - DB_POSTGRESDB_DATABASE_FILE=/run/secrets/DB_POSTGRESDB_DATABASE
      - DB_POSTGRESDB_SCHEMA_FILE=/run/secrets/DB_POSTGRESDB_SCHEMA
      - DB_POSTGRESDB_USER_FILE=/run/secrets/DB_POSTGRESDB_USER
      - DB_POSTGRESDB_PASSWORD_FILE=/run/secrets/DB_POSTGRESDB_PASSWORD

      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_LOG_LEVEL=info
      - N8N_DIAGNOSTICS_ENABLED=false
      - NODE_ENV=production
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    secrets:
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_ENCRYPTION_KEY
      - DB_POSTGRESDB_HOST
      - DB_POSTGRESDB_PORT
      - DB_POSTGRESDB_DATABASE
      - DB_POSTGRESDB_SCHEMA
      - DB_POSTGRESDB_USER
      - DB_POSTGRESDB_PASSWORD

secrets:
  N8N_BASIC_AUTH_USER:
    file: ./secrets/N8N_BASIC_AUTH_USER.txt
  N8N_BASIC_AUTH_PASSWORD:
    file: ./secrets/N8N_BASIC_AUTH_PASSWORD.txt
  N8N_ENCRYPTION_KEY:
    file: ./secrets/N8N_ENCRYPTION_KEY.txt
  DB_POSTGRESDB_HOST:
    file: ./secrets/DB_POSTGRESDB_HOST.txt
  DB_POSTGRESDB_PORT:
    file: ./secrets/DB_POSTGRESDB_PORT.txt
  DB_POSTGRESDB_DATABASE:
    file: ./secrets/DB_POSTGRESDB_DATABASE.txt
  DB_POSTGRESDB_SCHEMA:
    file: ./secrets/DB_POSTGRESDB_SCHEMA.txt
  DB_POSTGRESDB_USER:
    file: ./secrets/DB_POSTGRESDB_USER.txt
  DB_POSTGRESDB_PASSWORD:
    file: ./secrets/DB_POSTGRESDB_PASSWORD.txt

volumes:
  n8n_data:
    driver: local